//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-07/05/2013 05:25 AM(foreman)-)
//


package com.delta.schemas.SpecialPassengerInfoList;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HostContextParamsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HostContextParamsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="Airline" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="City" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="DutyCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="LogonId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Password" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="PoolType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ResetPassword" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="TimeoutInactivity" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="TimeoutSession" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HostContextParamsType", namespace = "http://schemas.delta.com/common/requestinfo/v4")
public class HostContextParamsType {

    @XmlAttribute(name = "Airline")
    protected String airline;
    @XmlAttribute(name = "City")
    protected String city;
    @XmlAttribute(name = "DutyCode")
    protected String dutyCode;
    @XmlAttribute(name = "LogonId")
    protected String logonId;
    @XmlAttribute(name = "Password")
    protected String password;
    @XmlAttribute(name = "PoolType")
    protected String poolType;
    @XmlAttribute(name = "ResetPassword")
    protected String resetPassword;
    @XmlAttribute(name = "TimeoutInactivity")
    protected String timeoutInactivity;
    @XmlAttribute(name = "TimeoutSession")
    protected String timeoutSession;

    /**
     * Gets the value of the airline property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAirline() {
        return airline;
    }

    /**
     * Sets the value of the airline property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAirline(String value) {
        this.airline = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the dutyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDutyCode() {
        return dutyCode;
    }

    /**
     * Sets the value of the dutyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDutyCode(String value) {
        this.dutyCode = value;
    }

    /**
     * Gets the value of the logonId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogonId() {
        return logonId;
    }

    /**
     * Sets the value of the logonId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogonId(String value) {
        this.logonId = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the poolType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPoolType() {
        return poolType;
    }

    /**
     * Sets the value of the poolType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPoolType(String value) {
        this.poolType = value;
    }

    /**
     * Gets the value of the resetPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResetPassword() {
        return resetPassword;
    }

    /**
     * Sets the value of the resetPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResetPassword(String value) {
        this.resetPassword = value;
    }

    /**
     * Gets the value of the timeoutInactivity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeoutInactivity() {
        return timeoutInactivity;
    }

    /**
     * Sets the value of the timeoutInactivity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeoutInactivity(String value) {
        this.timeoutInactivity = value;
    }

    /**
     * Gets the value of the timeoutSession property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeoutSession() {
        return timeoutSession;
    }

    /**
     * Sets the value of the timeoutSession property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeoutSession(String value) {
        this.timeoutSession = value;
    }

}
