//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-07/05/2013 05:25 AM(foreman)-)
//


package com.delta.schemas.SpecialPassengerInfoList;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PassengerInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PassengerInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="ActualCompartment" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ArrivalOrgAirportCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ArrivalSegOperatingAirlineCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ArrivalSegOperatingFlightNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="BookedCompartment" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="BookingCreationGDT" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="CheckInLocalDate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="CheckInLocalTime" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="CustomerId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="DestinationAirportCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="FileReceivedLocalDate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="FileReceivedLocalTimeStamp" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="FlightCancelInd" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="FrequentFlyerAirlineCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="FrequentFlyerId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="FrequentTierLevelDesc" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="GovtDocumentNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="InventoryClassCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="LegLocalDepartureDate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="LegLocalDepartureYearMonth" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="MultiDepartureSequenceNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="NextSegDstAirportCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="NextSegOperatingAirlineCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="NextSegOperatingFlightNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="OnBoardLocalDate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="OnBoardLocalTime" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="OperationalAirlineCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="OperationalFlightNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="OriginAirportCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="PnrLocatorNum" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="RecordProcessDate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="RowSeatNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SSRTypeCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SpilTypeCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="TicketDocumentIssueLocalDate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="TicketNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PassengerInfoType")
public class PassengerInfoType {

    @XmlAttribute(name = "ActualCompartment")
    protected String actualCompartment;
    @XmlAttribute(name = "ArrivalOrgAirportCode")
    protected String arrivalOrgAirportCode;
    @XmlAttribute(name = "ArrivalSegOperatingAirlineCode")
    protected String arrivalSegOperatingAirlineCode;
    @XmlAttribute(name = "ArrivalSegOperatingFlightNumber")
    protected String arrivalSegOperatingFlightNumber;
    @XmlAttribute(name = "BookedCompartment")
    protected String bookedCompartment;
    @XmlAttribute(name = "BookingCreationGDT")
    protected String bookingCreationGDT;
    @XmlAttribute(name = "CheckInLocalDate")
    protected String checkInLocalDate;
    @XmlAttribute(name = "CheckInLocalTime")
    protected String checkInLocalTime;
    @XmlAttribute(name = "CustomerId")
    protected String customerId;
    @XmlAttribute(name = "DestinationAirportCode")
    protected String destinationAirportCode;
    @XmlAttribute(name = "FileReceivedLocalDate")
    protected String fileReceivedLocalDate;
    @XmlAttribute(name = "FileReceivedLocalTimeStamp")
    protected String fileReceivedLocalTimeStamp;
    @XmlAttribute(name = "FlightCancelInd")
    protected String flightCancelInd;
    @XmlAttribute(name = "FrequentFlyerAirlineCode")
    protected String frequentFlyerAirlineCode;
    @XmlAttribute(name = "FrequentFlyerId")
    protected String frequentFlyerId;
    @XmlAttribute(name = "FrequentTierLevelDesc")
    protected String frequentTierLevelDesc;
    @XmlAttribute(name = "GovtDocumentNumber")
    protected String govtDocumentNumber;
    @XmlAttribute(name = "InventoryClassCode")
    protected String inventoryClassCode;
    @XmlAttribute(name = "LegLocalDepartureDate")
    protected String legLocalDepartureDate;
    @XmlAttribute(name = "LegLocalDepartureYearMonth")
    protected String legLocalDepartureYearMonth;
    @XmlAttribute(name = "MultiDepartureSequenceNumber")
    protected String multiDepartureSequenceNumber;
    @XmlAttribute(name = "Name")
    protected String name;
    @XmlAttribute(name = "NextSegDstAirportCode")
    protected String nextSegDstAirportCode;
    @XmlAttribute(name = "NextSegOperatingAirlineCode")
    protected String nextSegOperatingAirlineCode;
    @XmlAttribute(name = "NextSegOperatingFlightNumber")
    protected String nextSegOperatingFlightNumber;
    @XmlAttribute(name = "OnBoardLocalDate")
    protected String onBoardLocalDate;
    @XmlAttribute(name = "OnBoardLocalTime")
    protected String onBoardLocalTime;
    @XmlAttribute(name = "OperationalAirlineCode")
    protected String operationalAirlineCode;
    @XmlAttribute(name = "OperationalFlightNumber")
    protected String operationalFlightNumber;
    @XmlAttribute(name = "OriginAirportCode")
    protected String originAirportCode;
    @XmlAttribute(name = "PnrLocatorNum")
    protected String pnrLocatorNum;
    @XmlAttribute(name = "RecordProcessDate")
    protected String recordProcessDate;
    @XmlAttribute(name = "RowSeatNumber")
    protected String rowSeatNumber;
    @XmlAttribute(name = "SSRTypeCode")
    protected String ssrTypeCode;
    @XmlAttribute(name = "SpilTypeCode")
    protected String spilTypeCode;
    @XmlAttribute(name = "TicketDocumentIssueLocalDate")
    protected String ticketDocumentIssueLocalDate;
    @XmlAttribute(name = "TicketNumber")
    protected String ticketNumber;

    /**
     * Gets the value of the actualCompartment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActualCompartment() {
        return actualCompartment;
    }

    /**
     * Sets the value of the actualCompartment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActualCompartment(String value) {
        this.actualCompartment = value;
    }

    /**
     * Gets the value of the arrivalOrgAirportCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrivalOrgAirportCode() {
        return arrivalOrgAirportCode;
    }

    /**
     * Sets the value of the arrivalOrgAirportCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrivalOrgAirportCode(String value) {
        this.arrivalOrgAirportCode = value;
    }

    /**
     * Gets the value of the arrivalSegOperatingAirlineCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrivalSegOperatingAirlineCode() {
        return arrivalSegOperatingAirlineCode;
    }

    /**
     * Sets the value of the arrivalSegOperatingAirlineCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrivalSegOperatingAirlineCode(String value) {
        this.arrivalSegOperatingAirlineCode = value;
    }

    /**
     * Gets the value of the arrivalSegOperatingFlightNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrivalSegOperatingFlightNumber() {
        return arrivalSegOperatingFlightNumber;
    }

    /**
     * Sets the value of the arrivalSegOperatingFlightNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrivalSegOperatingFlightNumber(String value) {
        this.arrivalSegOperatingFlightNumber = value;
    }

    /**
     * Gets the value of the bookedCompartment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBookedCompartment() {
        return bookedCompartment;
    }

    /**
     * Sets the value of the bookedCompartment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBookedCompartment(String value) {
        this.bookedCompartment = value;
    }

    /**
     * Gets the value of the bookingCreationGDT property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBookingCreationGDT() {
        return bookingCreationGDT;
    }

    /**
     * Sets the value of the bookingCreationGDT property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBookingCreationGDT(String value) {
        this.bookingCreationGDT = value;
    }

    /**
     * Gets the value of the checkInLocalDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCheckInLocalDate() {
        return checkInLocalDate;
    }

    /**
     * Sets the value of the checkInLocalDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCheckInLocalDate(String value) {
        this.checkInLocalDate = value;
    }

    /**
     * Gets the value of the checkInLocalTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCheckInLocalTime() {
        return checkInLocalTime;
    }

    /**
     * Sets the value of the checkInLocalTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCheckInLocalTime(String value) {
        this.checkInLocalTime = value;
    }

    /**
     * Gets the value of the customerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * Sets the value of the customerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerId(String value) {
        this.customerId = value;
    }

    /**
     * Gets the value of the destinationAirportCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationAirportCode() {
        return destinationAirportCode;
    }

    /**
     * Sets the value of the destinationAirportCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationAirportCode(String value) {
        this.destinationAirportCode = value;
    }

    /**
     * Gets the value of the fileReceivedLocalDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileReceivedLocalDate() {
        return fileReceivedLocalDate;
    }

    /**
     * Sets the value of the fileReceivedLocalDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileReceivedLocalDate(String value) {
        this.fileReceivedLocalDate = value;
    }

    /**
     * Gets the value of the fileReceivedLocalTimeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileReceivedLocalTimeStamp() {
        return fileReceivedLocalTimeStamp;
    }

    /**
     * Sets the value of the fileReceivedLocalTimeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileReceivedLocalTimeStamp(String value) {
        this.fileReceivedLocalTimeStamp = value;
    }

    /**
     * Gets the value of the flightCancelInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlightCancelInd() {
        return flightCancelInd;
    }

    /**
     * Sets the value of the flightCancelInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlightCancelInd(String value) {
        this.flightCancelInd = value;
    }

    /**
     * Gets the value of the frequentFlyerAirlineCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrequentFlyerAirlineCode() {
        return frequentFlyerAirlineCode;
    }

    /**
     * Sets the value of the frequentFlyerAirlineCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrequentFlyerAirlineCode(String value) {
        this.frequentFlyerAirlineCode = value;
    }

    /**
     * Gets the value of the frequentFlyerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrequentFlyerId() {
        return frequentFlyerId;
    }

    /**
     * Sets the value of the frequentFlyerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrequentFlyerId(String value) {
        this.frequentFlyerId = value;
    }

    /**
     * Gets the value of the frequentTierLevelDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrequentTierLevelDesc() {
        return frequentTierLevelDesc;
    }

    /**
     * Sets the value of the frequentTierLevelDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrequentTierLevelDesc(String value) {
        this.frequentTierLevelDesc = value;
    }

    /**
     * Gets the value of the govtDocumentNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGovtDocumentNumber() {
        return govtDocumentNumber;
    }

    /**
     * Sets the value of the govtDocumentNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGovtDocumentNumber(String value) {
        this.govtDocumentNumber = value;
    }

    /**
     * Gets the value of the inventoryClassCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInventoryClassCode() {
        return inventoryClassCode;
    }

    /**
     * Sets the value of the inventoryClassCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInventoryClassCode(String value) {
        this.inventoryClassCode = value;
    }

    /**
     * Gets the value of the legLocalDepartureDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegLocalDepartureDate() {
        return legLocalDepartureDate;
    }

    /**
     * Sets the value of the legLocalDepartureDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegLocalDepartureDate(String value) {
        this.legLocalDepartureDate = value;
    }

    /**
     * Gets the value of the legLocalDepartureYearMonth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegLocalDepartureYearMonth() {
        return legLocalDepartureYearMonth;
    }

    /**
     * Sets the value of the legLocalDepartureYearMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegLocalDepartureYearMonth(String value) {
        this.legLocalDepartureYearMonth = value;
    }

    /**
     * Gets the value of the multiDepartureSequenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMultiDepartureSequenceNumber() {
        return multiDepartureSequenceNumber;
    }

    /**
     * Sets the value of the multiDepartureSequenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMultiDepartureSequenceNumber(String value) {
        this.multiDepartureSequenceNumber = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the nextSegDstAirportCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNextSegDstAirportCode() {
        return nextSegDstAirportCode;
    }

    /**
     * Sets the value of the nextSegDstAirportCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNextSegDstAirportCode(String value) {
        this.nextSegDstAirportCode = value;
    }

    /**
     * Gets the value of the nextSegOperatingAirlineCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNextSegOperatingAirlineCode() {
        return nextSegOperatingAirlineCode;
    }

    /**
     * Sets the value of the nextSegOperatingAirlineCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNextSegOperatingAirlineCode(String value) {
        this.nextSegOperatingAirlineCode = value;
    }

    /**
     * Gets the value of the nextSegOperatingFlightNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNextSegOperatingFlightNumber() {
        return nextSegOperatingFlightNumber;
    }

    /**
     * Sets the value of the nextSegOperatingFlightNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNextSegOperatingFlightNumber(String value) {
        this.nextSegOperatingFlightNumber = value;
    }

    /**
     * Gets the value of the onBoardLocalDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnBoardLocalDate() {
        return onBoardLocalDate;
    }

    /**
     * Sets the value of the onBoardLocalDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnBoardLocalDate(String value) {
        this.onBoardLocalDate = value;
    }

    /**
     * Gets the value of the onBoardLocalTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnBoardLocalTime() {
        return onBoardLocalTime;
    }

    /**
     * Sets the value of the onBoardLocalTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnBoardLocalTime(String value) {
        this.onBoardLocalTime = value;
    }

    /**
     * Gets the value of the operationalAirlineCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperationalAirlineCode() {
        return operationalAirlineCode;
    }

    /**
     * Sets the value of the operationalAirlineCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperationalAirlineCode(String value) {
        this.operationalAirlineCode = value;
    }

    /**
     * Gets the value of the operationalFlightNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperationalFlightNumber() {
        return operationalFlightNumber;
    }

    /**
     * Sets the value of the operationalFlightNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperationalFlightNumber(String value) {
        this.operationalFlightNumber = value;
    }

    /**
     * Gets the value of the originAirportCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginAirportCode() {
        return originAirportCode;
    }

    /**
     * Sets the value of the originAirportCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginAirportCode(String value) {
        this.originAirportCode = value;
    }

    /**
     * Gets the value of the pnrLocatorNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPnrLocatorNum() {
        return pnrLocatorNum;
    }

    /**
     * Sets the value of the pnrLocatorNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPnrLocatorNum(String value) {
        this.pnrLocatorNum = value;
    }

    /**
     * Gets the value of the recordProcessDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordProcessDate() {
        return recordProcessDate;
    }

    /**
     * Sets the value of the recordProcessDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordProcessDate(String value) {
        this.recordProcessDate = value;
    }

    /**
     * Gets the value of the rowSeatNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRowSeatNumber() {
        return rowSeatNumber;
    }

    /**
     * Sets the value of the rowSeatNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRowSeatNumber(String value) {
        this.rowSeatNumber = value;
    }

    /**
     * Gets the value of the ssrTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSSRTypeCode() {
        return ssrTypeCode;
    }

    /**
     * Sets the value of the ssrTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSSRTypeCode(String value) {
        this.ssrTypeCode = value;
    }

    /**
     * Gets the value of the spilTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpilTypeCode() {
        return spilTypeCode;
    }

    /**
     * Sets the value of the spilTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpilTypeCode(String value) {
        this.spilTypeCode = value;
    }

    /**
     * Gets the value of the ticketDocumentIssueLocalDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTicketDocumentIssueLocalDate() {
        return ticketDocumentIssueLocalDate;
    }

    /**
     * Sets the value of the ticketDocumentIssueLocalDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTicketDocumentIssueLocalDate(String value) {
        this.ticketDocumentIssueLocalDate = value;
    }

    /**
     * Gets the value of the ticketNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTicketNumber() {
        return ticketNumber;
    }

    /**
     * Sets the value of the ticketNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTicketNumber(String value) {
        this.ticketNumber = value;
    }

}
