//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-07/05/2013 05:25 AM(foreman)-)
//


package com.delta.schemas.SpecialPassengerInfoList;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RetrievePassengerRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RetrievePassengerRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://schemas.delta.com/common/requestinfo/v4}RequestInfo"/>
 *         &lt;element ref="{http://schemas.delta.com/specialpassengerinfolisttypes/v1}RetrievePassengerInfo"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RetrievePassengerRequestType", propOrder = {
    "requestInfo",
    "retrievePassengerInfo"
})
public class RetrievePassengerRequestType {

    @XmlElement(name = "RequestInfo", namespace = "http://schemas.delta.com/common/requestinfo/v4", required = true)
    protected RequestInfoType requestInfo;
    @XmlElement(name = "RetrievePassengerInfo", required = true)
    protected RetrievePassengerInfoType retrievePassengerInfo;

    /**
     * Gets the value of the requestInfo property.
     * 
     * @return
     *     possible object is
     *     {@link RequestInfoType }
     *     
     */
    public RequestInfoType getRequestInfo() {
        return requestInfo;
    }

    /**
     * Sets the value of the requestInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestInfoType }
     *     
     */
    public void setRequestInfo(RequestInfoType value) {
        this.requestInfo = value;
    }

    /**
     * Gets the value of the retrievePassengerInfo property.
     * 
     * @return
     *     possible object is
     *     {@link RetrievePassengerInfoType }
     *     
     */
    public RetrievePassengerInfoType getRetrievePassengerInfo() {
        return retrievePassengerInfo;
    }

    /**
     * Sets the value of the retrievePassengerInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link RetrievePassengerInfoType }
     *     
     */
    public void setRetrievePassengerInfo(RetrievePassengerInfoType value) {
        this.retrievePassengerInfo = value;
    }

}
