//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schemas.delta.com/common/ptrauthdata/v2")
package com.delta.schemas.common.ptrauthdata.v2;
