//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-07/05/2013 05:25 AM(foreman)-)
//


package com.delta.schemas.SpecialPassengerInfoListSI;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RetrievePassengerInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RetrievePassengerInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://schemas.delta.com/specialpassengerinfolisttypes/v1}FlightInquiryInfo"/>
 *         &lt;element ref="{http://schemas.delta.com/specialpassengerinfolisttypes/v1}LoyaltyInquiryInfo"/>
 *         &lt;element ref="{http://schemas.delta.com/specialpassengerinfolisttypes/v1}OtherInquiryInfo"/>
 *         &lt;element ref="{http://schemas.delta.com/specialpassengerinfolisttypes/v1}PassengerInquiryInfo"/>
 *       &lt;/choice>
 *       &lt;attribute name="OnDemandFileRcvdLclTms" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RetrievePassengerInfoType", propOrder = {
    "flightInquiryInfo",
    "loyaltyInquiryInfo",
    "otherInquiryInfo",
    "passengerInquiryInfo"
})
public class RetrievePassengerInfoType {

    @XmlElement(name = "FlightInquiryInfo")
    protected FlightInquiryInfoType flightInquiryInfo;
    @XmlElement(name = "LoyaltyInquiryInfo")
    protected LoyaltyInquiryInfoType loyaltyInquiryInfo;
    @XmlElement(name = "OtherInquiryInfo")
    protected OtherInquiryInfoType otherInquiryInfo;
    @XmlElement(name = "PassengerInquiryInfo")
    protected PassengerInquiryInfoType passengerInquiryInfo;
    @XmlAttribute(name = "OnDemandFileRcvdLclTms")
    protected String onDemandFileRcvdLclTms;

    /**
     * Gets the value of the flightInquiryInfo property.
     * 
     * @return
     *     possible object is
     *     {@link FlightInquiryInfoType }
     *     
     */
    public FlightInquiryInfoType getFlightInquiryInfo() {
        return flightInquiryInfo;
    }

    /**
     * Sets the value of the flightInquiryInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlightInquiryInfoType }
     *     
     */
    public void setFlightInquiryInfo(FlightInquiryInfoType value) {
        this.flightInquiryInfo = value;
    }

    /**
     * Gets the value of the loyaltyInquiryInfo property.
     * 
     * @return
     *     possible object is
     *     {@link LoyaltyInquiryInfoType }
     *     
     */
    public LoyaltyInquiryInfoType getLoyaltyInquiryInfo() {
        return loyaltyInquiryInfo;
    }

    /**
     * Sets the value of the loyaltyInquiryInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoyaltyInquiryInfoType }
     *     
     */
    public void setLoyaltyInquiryInfo(LoyaltyInquiryInfoType value) {
        this.loyaltyInquiryInfo = value;
    }

    /**
     * Gets the value of the otherInquiryInfo property.
     * 
     * @return
     *     possible object is
     *     {@link OtherInquiryInfoType }
     *     
     */
    public OtherInquiryInfoType getOtherInquiryInfo() {
        return otherInquiryInfo;
    }

    /**
     * Sets the value of the otherInquiryInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link OtherInquiryInfoType }
     *     
     */
    public void setOtherInquiryInfo(OtherInquiryInfoType value) {
        this.otherInquiryInfo = value;
    }

    /**
     * Gets the value of the passengerInquiryInfo property.
     * 
     * @return
     *     possible object is
     *     {@link PassengerInquiryInfoType }
     *     
     */
    public PassengerInquiryInfoType getPassengerInquiryInfo() {
        return passengerInquiryInfo;
    }

    /**
     * Sets the value of the passengerInquiryInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PassengerInquiryInfoType }
     *     
     */
    public void setPassengerInquiryInfo(PassengerInquiryInfoType value) {
        this.passengerInquiryInfo = value;
    }

    /**
     * Gets the value of the onDemandFileRcvdLclTms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnDemandFileRcvdLclTms() {
        return onDemandFileRcvdLclTms;
    }

    /**
     * Sets the value of the onDemandFileRcvdLclTms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnDemandFileRcvdLclTms(String value) {
        this.onDemandFileRcvdLclTms = value;
    }

}
