//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-07/05/2013 05:25 AM(foreman)-)
//


package com.delta.soa.updated.PCiTokenManager;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DecodeArrayOfTokensResult" type="{http://schemas.delta.com/pci/v1/pcitokenmgrresp}PciTokMgrResponse" form="unqualified"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "decodeArrayOfTokensResult"
})
@XmlRootElement(name = "DecodeArrayOfTokensResponse")
public class DecodeArrayOfTokensResponse {

    @XmlElement(name = "DecodeArrayOfTokensResult", required = true)
    protected PciTokMgrResponse decodeArrayOfTokensResult;

    /**
     * Gets the value of the decodeArrayOfTokensResult property.
     * 
     * @return
     *     possible object is
     *     {@link PciTokMgrResponse }
     *     
     */
    public PciTokMgrResponse getDecodeArrayOfTokensResult() {
        return decodeArrayOfTokensResult;
    }

    /**
     * Sets the value of the decodeArrayOfTokensResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link PciTokMgrResponse }
     *     
     */
    public void setDecodeArrayOfTokensResult(PciTokMgrResponse value) {
        this.decodeArrayOfTokensResult = value;
    }

}
