//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-07/05/2013 05:25 AM(foreman)-)
//


package com.delta.soa.updated.PCiTokenManager;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="requestInfo" type="{http://schemas.delta.com/pci/v1/requestinfo}PciRequestInfo" form="unqualified"/>
 *         &lt;element name="creditCardNumList" type="{http://soa.delta.com/pci/soagov/v1}ArrayOfString" form="unqualified"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "requestInfo",
    "creditCardNumList"
})
@XmlRootElement(name = "LookupArrayOfTokensRequest")
public class LookupArrayOfTokensRequest {

    @XmlElement(required = true)
    protected PciRequestInfo requestInfo;
    @XmlElement(required = true)
    protected ArrayOfString creditCardNumList;

    /**
     * Gets the value of the requestInfo property.
     * 
     * @return
     *     possible object is
     *     {@link PciRequestInfo }
     *     
     */
    public PciRequestInfo getRequestInfo() {
        return requestInfo;
    }

    /**
     * Sets the value of the requestInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PciRequestInfo }
     *     
     */
    public void setRequestInfo(PciRequestInfo value) {
        this.requestInfo = value;
    }

    /**
     * Gets the value of the creditCardNumList property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfString }
     *     
     */
    public ArrayOfString getCreditCardNumList() {
        return creditCardNumList;
    }

    /**
     * Sets the value of the creditCardNumList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfString }
     *     
     */
    public void setCreditCardNumList(ArrayOfString value) {
        this.creditCardNumList = value;
    }

}
