//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.delta.schemas.common.checkhealth.v3;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.delta.schemas.common.checkhealth.v3 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CheckHealthResponse_QNAME = new QName("http://schemas.delta.com/common/checkhealth/v3", "CheckHealthResponse");
    private final static QName _CheckHealthRequest_QNAME = new QName("http://schemas.delta.com/common/checkhealth/v3", "CheckHealthRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.delta.schemas.common.checkhealth.v3
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CheckHealthGenericRequestType }
     * 
     */
    public CheckHealthGenericRequestType createCheckHealthGenericRequestType() {
        return new CheckHealthGenericRequestType();
    }

    /**
     * Create an instance of {@link HealthMessageType }
     * 
     */
    public HealthMessageType createHealthMessageType() {
        return new HealthMessageType();
    }

    /**
     * Create an instance of {@link CheckHealthResponseType }
     * 
     */
    public CheckHealthResponseType createCheckHealthResponseType() {
        return new CheckHealthResponseType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CheckHealthResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.delta.com/common/checkhealth/v3", name = "CheckHealthResponse")
    public JAXBElement<CheckHealthResponseType> createCheckHealthResponse(CheckHealthResponseType value) {
        return new JAXBElement<CheckHealthResponseType>(_CheckHealthResponse_QNAME, CheckHealthResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CheckHealthGenericRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.delta.com/common/checkhealth/v3", name = "CheckHealthRequest")
    public JAXBElement<CheckHealthGenericRequestType> createCheckHealthRequest(CheckHealthGenericRequestType value) {
        return new JAXBElement<CheckHealthGenericRequestType>(_CheckHealthRequest_QNAME, CheckHealthGenericRequestType.class, null, value);
    }

}
