//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-07/05/2013 05:25 AM(foreman)-)
//


package com.delta.soa.specialpassengerinfolist.ST;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StampingInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StampingInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://schemas.delta.com/common/userauthdata/v2}UserAuthorizationData" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.delta.com/common/ptrauthdata/v2}PrinterAuthorizationData" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StampingInfoType", namespace = "http://schemas.delta.com/common/stamping/v2", propOrder = {
    "userAuthorizationData",
    "printerAuthorizationData"
})
public class StampingInfoType {

    @XmlElement(name = "UserAuthorizationData", namespace = "http://schemas.delta.com/common/userauthdata/v2")
    protected UserAuthorizationDataType userAuthorizationData;
    @XmlElement(name = "PrinterAuthorizationData", namespace = "http://schemas.delta.com/common/ptrauthdata/v2")
    protected PrinterAuthorizationDataType printerAuthorizationData;

    /**
     * Gets the value of the userAuthorizationData property.
     * 
     * @return
     *     possible object is
     *     {@link UserAuthorizationDataType }
     *     
     */
    public UserAuthorizationDataType getUserAuthorizationData() {
        return userAuthorizationData;
    }

    /**
     * Sets the value of the userAuthorizationData property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserAuthorizationDataType }
     *     
     */
    public void setUserAuthorizationData(UserAuthorizationDataType value) {
        this.userAuthorizationData = value;
    }

    /**
     * Gets the value of the printerAuthorizationData property.
     * 
     * @return
     *     possible object is
     *     {@link PrinterAuthorizationDataType }
     *     
     */
    public PrinterAuthorizationDataType getPrinterAuthorizationData() {
        return printerAuthorizationData;
    }

    /**
     * Sets the value of the printerAuthorizationData property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrinterAuthorizationDataType }
     *     
     */
    public void setPrinterAuthorizationData(PrinterAuthorizationDataType value) {
        this.printerAuthorizationData = value;
    }

}
