//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.delta.soa.specialpassengerinfolist;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.delta.schemas.common.checkhealth.v3.CheckHealthGenericRequestType;
import com.delta.schemas.common.checkhealth.v3.CheckHealthResponseType;
import com.delta.schemas.specialpassengerinfolisttypes.v1.OnDemandRequestType;
import com.delta.schemas.specialpassengerinfolisttypes.v1.OnDemandResponseType;
import com.delta.schemas.specialpassengerinfolisttypes.v1.RetrievePassengerRequestType;
import com.delta.schemas.specialpassengerinfolisttypes.v1.RetrievePassengerResponseType;
import com.delta.schemas.specialpassengerinfolisttypes.v1.RetrieveSSRRequestType;
import com.delta.schemas.specialpassengerinfolisttypes.v1.RetrieveSSRResponseType;
import com.delta.schemas.specialpassengerinfolisttypes.v1.RetrieveWaitListRequestType;
import com.delta.schemas.specialpassengerinfolisttypes.v1.RetrieveWaitListResponseType;

@WebService(name = "SpecialPassengerInfoList", targetNamespace = "http://soa.delta.com/specialpassengerinfolist")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.delta.schemas.specialpassengerinfolisttypes.v1.ObjectFactory.class,
    com.delta.schemas.common.debuginfo.v4.ObjectFactory.class,
    com.delta.schemas.common.userauthdata.v2.ObjectFactory.class,
    com.delta.schemas.common.requestinfo.v4.ObjectFactory.class,
    com.delta.schemas.common.ptrauthdata.v2.ObjectFactory.class,
    com.delta.schemas.common.fault.v4.ObjectFactory.class,
    com.delta.schemas.common.advisorymessage.v2.ObjectFactory.class,
    com.delta.schemas.common.responseinfo.v1.ObjectFactory.class,
    com.delta.schemas.common.checkhealth.v3.ObjectFactory.class,
    com.delta.schemas.common.stamping.v2.ObjectFactory.class
})
public interface SpecialPassengerInfoList {


    /**
     * 
     * @param params
     * @return
     *     returns com.delta.schemas.common.checkhealth.v3.CheckHealthResponseType
     */
    @WebMethod(operationName = "CheckHealth", action = "CheckHealth")
    @WebResult(name = "CheckHealthResponse", targetNamespace = "http://schemas.delta.com/common/checkhealth/v3", partName = "params")
    public CheckHealthResponseType checkHealth(
        @WebParam(name = "CheckHealthRequest", targetNamespace = "http://schemas.delta.com/common/checkhealth/v3", partName = "params")
        CheckHealthGenericRequestType params);

    /**
     * 
     * @param params
     * @return
     *     returns com.delta.schemas.specialpassengerinfolisttypes.v1.RetrieveSSRResponseType
     * @throws SystemFault
     * @throws BusinessFault
     */
    @WebMethod(operationName = "RetrieveSSR", action = "RetrieveSSR")
    @WebResult(name = "RetrieveSSRResponse", targetNamespace = "http://schemas.delta.com/specialpassengerinfolisttypes/v1", partName = "params")
    public RetrieveSSRResponseType retrieveSSR(
        @WebParam(name = "RetrieveSSRRequest", targetNamespace = "http://schemas.delta.com/specialpassengerinfolisttypes/v1", partName = "params")
        RetrieveSSRRequestType params)
        throws BusinessFault, SystemFault
    ;

    /**
     * 
     * @param params
     * @return
     *     returns com.delta.schemas.specialpassengerinfolisttypes.v1.OnDemandResponseType
     * @throws SystemFault
     * @throws BusinessFault
     */
    @WebMethod(operationName = "OnDemand", action = "OnDemandPush")
    @WebResult(name = "OnDemandResponse", targetNamespace = "http://schemas.delta.com/specialpassengerinfolisttypes/v1", partName = "params")
    public OnDemandResponseType onDemand(
        @WebParam(name = "OnDemandRequest", targetNamespace = "http://schemas.delta.com/specialpassengerinfolisttypes/v1", partName = "params")
        OnDemandRequestType params)
        throws BusinessFault, SystemFault
    ;

    /**
     * 
     * @param params
     * @return
     *     returns com.delta.schemas.specialpassengerinfolisttypes.v1.RetrievePassengerResponseType
     * @throws SystemFault
     * @throws BusinessFault
     */
    @WebMethod(operationName = "RetrievePassenger", action = "Retrieve")
    @WebResult(name = "RetrievePassengerResponse", targetNamespace = "http://schemas.delta.com/specialpassengerinfolisttypes/v1", partName = "params")
    public RetrievePassengerResponseType retrievePassenger(
        @WebParam(name = "RetrievePassengerRequest", targetNamespace = "http://schemas.delta.com/specialpassengerinfolisttypes/v1", partName = "params")
        RetrievePassengerRequestType params)
        throws BusinessFault, SystemFault
    ;

    /**
     * 
     * @param params
     * @return
     *     returns com.delta.schemas.specialpassengerinfolisttypes.v1.RetrieveWaitListResponseType
     * @throws SystemFault
     * @throws BusinessFault
     */
    @WebMethod(operationName = "RetrieveWaitList", action = "RetrieveWaitList")
    @WebResult(name = "RetrieveWaitListResponse", targetNamespace = "http://schemas.delta.com/specialpassengerinfolisttypes/v1", partName = "params")
    public RetrieveWaitListResponseType retrieveWaitList(
        @WebParam(name = "RetrieveWaitListRequest", targetNamespace = "http://schemas.delta.com/specialpassengerinfolisttypes/v1", partName = "params")
        RetrieveWaitListRequestType params)
        throws BusinessFault, SystemFault
    ;

}
