//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.delta.soa.specialpassengerinfolist;

import javax.xml.ws.WebFault;
import com.delta.schemas.common.fault.v4.SystemFaultType;

@WebFault(name = "SystemFault", targetNamespace = "http://schemas.delta.com/common/fault/v4")
public class SystemFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SystemFaultType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public SystemFault(String message, SystemFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public SystemFault(String message, SystemFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.delta.schemas.common.fault.v4.SystemFaultType
     */
    public SystemFaultType getFaultInfo() {
        return faultInfo;
    }

}
