//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.delta.schemas.common.responseinfo.v1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.delta.schemas.common.responseinfo.v1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ResponseInfo_QNAME = new QName("http://schemas.delta.com/common/responseinfo/v1", "ResponseInfo");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.delta.schemas.common.responseinfo.v1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ResponseInfoType }
     * 
     */
    public ResponseInfoType createResponseInfoType() {
        return new ResponseInfoType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponseInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.delta.com/common/responseinfo/v1", name = "ResponseInfo")
    public JAXBElement<ResponseInfoType> createResponseInfo(ResponseInfoType value) {
        return new JAXBElement<ResponseInfoType>(_ResponseInfo_QNAME, ResponseInfoType.class, null, value);
    }

}
