//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-07/05/2013 05:25 AM(foreman)-)
//


package com.delta.soa.specialpassengerinfolist.ST;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				RequestType that will accept a string. If the check
 * 				health function does not require any special inputs, use
 * 				this request type.
 * 			
 * 
 * <p>Java class for CheckHealthGenericRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CheckHealthGenericRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AnyString" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CheckHealthGenericRequestType", namespace = "http://schemas.delta.com/common/checkhealth/v3", propOrder = {
    "anyString"
})
public class CheckHealthGenericRequestType {

    @XmlElement(name = "AnyString", required = true)
    protected String anyString;

    /**
     * Gets the value of the anyString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnyString() {
        return anyString;
    }

    /**
     * Sets the value of the anyString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnyString(String value) {
        this.anyString = value;
    }

}
