//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-07/05/2013 05:25 AM(foreman)-)
//


package com.delta.soa.specialpassengerinfolist.ST;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HealthStatusType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="HealthStatusType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="FATAL"/>
 *     &lt;enumeration value="WARN"/>
 *     &lt;enumeration value="OK"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "HealthStatusType", namespace = "http://schemas.delta.com/common/checkhealth/v3")
@XmlEnum
public enum HealthStatusType {


    /**
     * FATAL : cannot achieve desired goals which are considered critical by the provider
     * 
     */
    FATAL,

    /**
     * WARN : certain pieces of the service may not be functioning properly, but the overall goals of the provider is still achieved
     * 
     */
    WARN,

    /**
     * OK : no problems of any kind were detected
     * 
     */
    OK;

    public String value() {
        return name();
    }

    public static HealthStatusType fromValue(String v) {
        return valueOf(v);
    }

}
