//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-07/05/2013 05:25 AM(foreman)-)
//


package com.delta.soa.specialpassengerinfolist.ST;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

@WebService(name = "SpecialPassengerInfoList", targetNamespace = "http://soa.delta.com/specialpassengerinfolist")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SpecialPassengerInfoList {


    /**
     * 
     * @param params
     * @return
     *     returns com.delta.soa.specialpassengerinfolist.ST.CheckHealthResponseType
     */
    @WebMethod(operationName = "CheckHealth", action = "CheckHealth")
    @WebResult(name = "CheckHealthResponse", targetNamespace = "http://schemas.delta.com/common/checkhealth/v3", partName = "params")
    public CheckHealthResponseType checkHealth(
        @WebParam(name = "CheckHealthRequest", targetNamespace = "http://schemas.delta.com/common/checkhealth/v3", partName = "params")
        CheckHealthGenericRequestType params);

    /**
     * 
     * @param params
     * @return
     *     returns com.delta.soa.specialpassengerinfolist.ST.RetrieveSSRResponseType
     * @throws SystemFault
     * @throws BusinessFault
     */
    @WebMethod(operationName = "RetrieveSSR", action = "RetrieveSSR")
    @WebResult(name = "RetrieveSSRResponse", targetNamespace = "http://schemas.delta.com/specialpassengerinfolisttypes/v1", partName = "params")
    public RetrieveSSRResponseType retrieveSSR(
        @WebParam(name = "RetrieveSSRRequest", targetNamespace = "http://schemas.delta.com/specialpassengerinfolisttypes/v1", partName = "params")
        RetrieveSSRRequestType params)
        throws BusinessFault, SystemFault
    ;

    /**
     * 
     * @param params
     * @return
     *     returns com.delta.soa.specialpassengerinfolist.ST.OnDemandResponseType
     * @throws SystemFault
     * @throws BusinessFault
     */
    @WebMethod(operationName = "OnDemand", action = "OnDemandPush")
    @WebResult(name = "OnDemandResponse", targetNamespace = "http://schemas.delta.com/specialpassengerinfolisttypes/v1", partName = "params")
    public OnDemandResponseType onDemand(
        @WebParam(name = "OnDemandRequest", targetNamespace = "http://schemas.delta.com/specialpassengerinfolisttypes/v1", partName = "params")
        OnDemandRequestType params)
        throws BusinessFault, SystemFault
    ;

    /**
     * 
     * @param params
     * @return
     *     returns com.delta.soa.specialpassengerinfolist.ST.RetrievePassengerResponseType
     * @throws SystemFault
     * @throws BusinessFault
     */
    @WebMethod(operationName = "RetrievePassenger", action = "Retrieve")
    @WebResult(name = "RetrievePassengerResponse", targetNamespace = "http://schemas.delta.com/specialpassengerinfolisttypes/v1", partName = "params")
    public RetrievePassengerResponseType retrievePassenger(
        @WebParam(name = "RetrievePassengerRequest", targetNamespace = "http://schemas.delta.com/specialpassengerinfolisttypes/v1", partName = "params")
        RetrievePassengerRequestType params)
        throws BusinessFault, SystemFault
    ;

    /**
     * 
     * @param params
     * @return
     *     returns com.delta.soa.specialpassengerinfolist.ST.RetrieveWaitListResponseType
     * @throws SystemFault
     * @throws BusinessFault
     */
    @WebMethod(operationName = "RetrieveWaitList", action = "RetrieveWaitList")
    @WebResult(name = "RetrieveWaitListResponse", targetNamespace = "http://schemas.delta.com/specialpassengerinfolisttypes/v1", partName = "params")
    public RetrieveWaitListResponseType retrieveWaitList(
        @WebParam(name = "RetrieveWaitListRequest", targetNamespace = "http://schemas.delta.com/specialpassengerinfolisttypes/v1", partName = "params")
        RetrieveWaitListRequestType params)
        throws BusinessFault, SystemFault
    ;

}
