//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package com.delta.schemas.pci.v1.requestinfo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * PciTokRequestInfo documents convey request metadata to the various PCI Tokenization web services.
 * 
 * <p>Java class for PciRequestInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PciRequestInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="AgentDutyCode">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[a-zA-Z]{1,2}"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="AgentSineCode">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[a-zA-Z]{1,2}"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="AppChannelName" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[a-zA-Z0-9_\.]{1,8}"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="AppCompanyName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="AppName" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[a-zA-Z0-9_\.]{1,20}"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="AppVersion">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[Vv](\d+\.){3}\d+"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="BackendHostId" default="TPF">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="([Tt][Pp][Ff]|[Zz][Oo][Ss])"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="CorrelationId">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value=".{1,20}"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="DeltaPassportUserId">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[a-zA-Z0-9]{9,10}"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="DeltamaticUserId">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[A-Z0-9]{6,10}"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="IsAppInternal" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="IsDebugInfoRequested" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="NetworkAddress">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="((\d{1,3}\.){3}\d{1,3}|[a-zA-Z0-9]{1,15})"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="WorkstationName">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[a-zA-Z0-9]{1,20}"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PciRequestInfo", namespace = "http://schemas.delta.com/pci/v1/requestinfo")
public class PciRequestInfo {

    @XmlAttribute(name = "AgentDutyCode")
    protected String agentDutyCode;
    @XmlAttribute(name = "AgentSineCode")
    protected String agentSineCode;
    @XmlAttribute(name = "AppChannelName", required = true)
    protected String appChannelName;
    @XmlAttribute(name = "AppCompanyName")
    protected String appCompanyName;
    @XmlAttribute(name = "AppName", required = true)
    protected String appName;
    @XmlAttribute(name = "AppVersion")
    protected String appVersion;
    @XmlAttribute(name = "BackendHostId")
    protected String backendHostId;
    @XmlAttribute(name = "CorrelationId")
    protected String correlationId;
    @XmlAttribute(name = "DeltaPassportUserId")
    protected String deltaPassportUserId;
    @XmlAttribute(name = "DeltamaticUserId")
    protected String deltamaticUserId;
    @XmlAttribute(name = "IsAppInternal", required = true)
    protected boolean isAppInternal;
    @XmlAttribute(name = "IsDebugInfoRequested", required = true)
    protected boolean isDebugInfoRequested;
    @XmlAttribute(name = "NetworkAddress")
    protected String networkAddress;
    @XmlAttribute(name = "WorkstationName")
    protected String workstationName;

    /**
     * Gets the value of the agentDutyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgentDutyCode() {
        return agentDutyCode;
    }

    /**
     * Sets the value of the agentDutyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgentDutyCode(String value) {
        this.agentDutyCode = value;
    }

    /**
     * Gets the value of the agentSineCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgentSineCode() {
        return agentSineCode;
    }

    /**
     * Sets the value of the agentSineCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgentSineCode(String value) {
        this.agentSineCode = value;
    }

    /**
     * Gets the value of the appChannelName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppChannelName() {
        return appChannelName;
    }

    /**
     * Sets the value of the appChannelName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppChannelName(String value) {
        this.appChannelName = value;
    }

    /**
     * Gets the value of the appCompanyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppCompanyName() {
        return appCompanyName;
    }

    /**
     * Sets the value of the appCompanyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppCompanyName(String value) {
        this.appCompanyName = value;
    }

    /**
     * Gets the value of the appName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppName() {
        return appName;
    }

    /**
     * Sets the value of the appName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppName(String value) {
        this.appName = value;
    }

    /**
     * Gets the value of the appVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppVersion() {
        return appVersion;
    }

    /**
     * Sets the value of the appVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppVersion(String value) {
        this.appVersion = value;
    }

    /**
     * Gets the value of the backendHostId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackendHostId() {
        if (backendHostId == null) {
            return "TPF";
        } else {
            return backendHostId;
        }
    }

    /**
     * Sets the value of the backendHostId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackendHostId(String value) {
        this.backendHostId = value;
    }

    /**
     * Gets the value of the correlationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorrelationId() {
        return correlationId;
    }

    /**
     * Sets the value of the correlationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorrelationId(String value) {
        this.correlationId = value;
    }

    /**
     * Gets the value of the deltaPassportUserId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeltaPassportUserId() {
        return deltaPassportUserId;
    }

    /**
     * Sets the value of the deltaPassportUserId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeltaPassportUserId(String value) {
        this.deltaPassportUserId = value;
    }

    /**
     * Gets the value of the deltamaticUserId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeltamaticUserId() {
        return deltamaticUserId;
    }

    /**
     * Sets the value of the deltamaticUserId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeltamaticUserId(String value) {
        this.deltamaticUserId = value;
    }

    /**
     * Gets the value of the isAppInternal property.
     * 
     */
    public boolean isIsAppInternal() {
        return isAppInternal;
    }

    /**
     * Sets the value of the isAppInternal property.
     * 
     */
    public void setIsAppInternal(boolean value) {
        this.isAppInternal = value;
    }

    /**
     * Gets the value of the isDebugInfoRequested property.
     * 
     */
    public boolean isIsDebugInfoRequested() {
        return isDebugInfoRequested;
    }

    /**
     * Sets the value of the isDebugInfoRequested property.
     * 
     */
    public void setIsDebugInfoRequested(boolean value) {
        this.isDebugInfoRequested = value;
    }

    /**
     * Gets the value of the networkAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetworkAddress() {
        return networkAddress;
    }

    /**
     * Sets the value of the networkAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetworkAddress(String value) {
        this.networkAddress = value;
    }

    /**
     * Gets the value of the workstationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkstationName() {
        return workstationName;
    }

    /**
     * Sets the value of the workstationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkstationName(String value) {
        this.workstationName = value;
    }

}
