//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.delta.schemas.common.requestinfo.v4;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DBConnectionInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DBConnectionInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="BedsDBDnsNameId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="TestBedsDBId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="TestFpesDBId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DBConnectionInfoType", namespace = "http://schemas.delta.com/common/requestinfo/v4")
public class DBConnectionInfoType {

    @XmlAttribute(name = "BedsDBDnsNameId")
    protected String bedsDBDnsNameId;
    @XmlAttribute(name = "TestBedsDBId")
    protected String testBedsDBId;
    @XmlAttribute(name = "TestFpesDBId")
    protected String testFpesDBId;

    /**
     * Gets the value of the bedsDBDnsNameId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBedsDBDnsNameId() {
        return bedsDBDnsNameId;
    }

    /**
     * Sets the value of the bedsDBDnsNameId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBedsDBDnsNameId(String value) {
        this.bedsDBDnsNameId = value;
    }

    /**
     * Gets the value of the testBedsDBId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestBedsDBId() {
        return testBedsDBId;
    }

    /**
     * Sets the value of the testBedsDBId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestBedsDBId(String value) {
        this.testBedsDBId = value;
    }

    /**
     * Gets the value of the testFpesDBId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestFpesDBId() {
        return testFpesDBId;
    }

    /**
     * Sets the value of the testFpesDBId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestFpesDBId(String value) {
        this.testFpesDBId = value;
    }

}
