//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.delta.schemas.common.requestinfo.v4;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.delta.schemas.common.requestinfo.v4 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RequestInfo_QNAME = new QName("http://schemas.delta.com/common/requestinfo/v4", "RequestInfo");
    private final static QName _DBConnectionInfo_QNAME = new QName("http://schemas.delta.com/common/requestinfo/v4", "DBConnectionInfo");
    private final static QName _HostContextParams_QNAME = new QName("http://schemas.delta.com/common/requestinfo/v4", "HostContextParams");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.delta.schemas.common.requestinfo.v4
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RequestInfoType }
     * 
     */
    public RequestInfoType createRequestInfoType() {
        return new RequestInfoType();
    }

    /**
     * Create an instance of {@link DBConnectionInfoType }
     * 
     */
    public DBConnectionInfoType createDBConnectionInfoType() {
        return new DBConnectionInfoType();
    }

    /**
     * Create an instance of {@link HostContextParamsType }
     * 
     */
    public HostContextParamsType createHostContextParamsType() {
        return new HostContextParamsType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.delta.com/common/requestinfo/v4", name = "RequestInfo")
    public JAXBElement<RequestInfoType> createRequestInfo(RequestInfoType value) {
        return new JAXBElement<RequestInfoType>(_RequestInfo_QNAME, RequestInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DBConnectionInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.delta.com/common/requestinfo/v4", name = "DBConnectionInfo")
    public JAXBElement<DBConnectionInfoType> createDBConnectionInfo(DBConnectionInfoType value) {
        return new JAXBElement<DBConnectionInfoType>(_DBConnectionInfo_QNAME, DBConnectionInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HostContextParamsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.delta.com/common/requestinfo/v4", name = "HostContextParams")
    public JAXBElement<HostContextParamsType> createHostContextParams(HostContextParamsType value) {
        return new JAXBElement<HostContextParamsType>(_HostContextParams_QNAME, HostContextParamsType.class, null, value);
    }

}
