//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package com.delta.schemas.pci.v1.pciitemstat;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import com.delta.schemas.pci.v1.pcipan.PciPan;
import com.delta.schemas.pci.v1.pcitoken.PciToken;
import com.delta.schemas.pci.v1.requestinfo.PciRequestInfo;


/**
 * A representation of a status event (or log entry) for a PCI service operation call. PCITokItemStatus docs are generated in response to token operation calls and audit log queries.
 * 
 * <p>Java class for PciTokItemStatus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PciTokItemStatus">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OperationTimestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="Token" type="{http://schemas.delta.com/pci/v1/pcitoken}PciToken" minOccurs="0"/>
 *         &lt;element name="CreditCardNumber" type="{http://schemas.delta.com/pci/v1/pcipan}PciPan" minOccurs="0"/>
 *         &lt;element name="PciRequestInfo" type="{http://schemas.delta.com/pci/v1/requestinfo}PciRequestInfo" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="BackendHandlerId">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="\w{3}"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="OperationName">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="\w{1,64}"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="RawTraceText">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value=".*"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="ReasonCode" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="\d{3}"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="ReasonText">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value=".*"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="StatusCode" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="\d{3}"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="StatusText">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value=".*"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="TransactionHistorySequenceNumber" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PciTokItemStatus", namespace = "http://schemas.delta.com/pci/v1/pciitemstat", propOrder = {
    "operationTimestamp",
    "token",
    "creditCardNumber",
    "pciRequestInfo"
})
public class PciTokItemStatus {

    @XmlElement(name = "OperationTimestamp", required = true, nillable = true)
    protected XMLGregorianCalendar operationTimestamp;
    @XmlElement(name = "Token")
    protected PciToken token;
    @XmlElement(name = "CreditCardNumber")
    protected PciPan creditCardNumber;
    @XmlElement(name = "PciRequestInfo")
    protected PciRequestInfo pciRequestInfo;
    @XmlAttribute(name = "BackendHandlerId")
    protected String backendHandlerId;
    @XmlAttribute(name = "OperationName")
    protected String operationName;
    @XmlAttribute(name = "RawTraceText")
    protected String rawTraceText;
    @XmlAttribute(name = "ReasonCode", required = true)
    protected String reasonCode;
    @XmlAttribute(name = "ReasonText")
    protected String reasonText;
    @XmlAttribute(name = "StatusCode", required = true)
    protected String statusCode;
    @XmlAttribute(name = "StatusText")
    protected String statusText;
    @XmlAttribute(name = "TransactionHistorySequenceNumber")
    protected Integer transactionHistorySequenceNumber;

    /**
     * Gets the value of the operationTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOperationTimestamp() {
        return operationTimestamp;
    }

    /**
     * Sets the value of the operationTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOperationTimestamp(XMLGregorianCalendar value) {
        this.operationTimestamp = value;
    }

    /**
     * Gets the value of the token property.
     * 
     * @return
     *     possible object is
     *     {@link PciToken }
     *     
     */
    public PciToken getToken() {
        return token;
    }

    /**
     * Sets the value of the token property.
     * 
     * @param value
     *     allowed object is
     *     {@link PciToken }
     *     
     */
    public void setToken(PciToken value) {
        this.token = value;
    }

    /**
     * Gets the value of the creditCardNumber property.
     * 
     * @return
     *     possible object is
     *     {@link PciPan }
     *     
     */
    public PciPan getCreditCardNumber() {
        return creditCardNumber;
    }

    /**
     * Sets the value of the creditCardNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link PciPan }
     *     
     */
    public void setCreditCardNumber(PciPan value) {
        this.creditCardNumber = value;
    }

    /**
     * Gets the value of the pciRequestInfo property.
     * 
     * @return
     *     possible object is
     *     {@link PciRequestInfo }
     *     
     */
    public PciRequestInfo getPciRequestInfo() {
        return pciRequestInfo;
    }

    /**
     * Sets the value of the pciRequestInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PciRequestInfo }
     *     
     */
    public void setPciRequestInfo(PciRequestInfo value) {
        this.pciRequestInfo = value;
    }

    /**
     * Gets the value of the backendHandlerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackendHandlerId() {
        return backendHandlerId;
    }

    /**
     * Sets the value of the backendHandlerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackendHandlerId(String value) {
        this.backendHandlerId = value;
    }

    /**
     * Gets the value of the operationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperationName() {
        return operationName;
    }

    /**
     * Sets the value of the operationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperationName(String value) {
        this.operationName = value;
    }

    /**
     * Gets the value of the rawTraceText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRawTraceText() {
        return rawTraceText;
    }

    /**
     * Sets the value of the rawTraceText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRawTraceText(String value) {
        this.rawTraceText = value;
    }

    /**
     * Gets the value of the reasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReasonCode() {
        return reasonCode;
    }

    /**
     * Sets the value of the reasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReasonCode(String value) {
        this.reasonCode = value;
    }

    /**
     * Gets the value of the reasonText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReasonText() {
        return reasonText;
    }

    /**
     * Sets the value of the reasonText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReasonText(String value) {
        this.reasonText = value;
    }

    /**
     * Gets the value of the statusCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusCode() {
        return statusCode;
    }

    /**
     * Sets the value of the statusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusCode(String value) {
        this.statusCode = value;
    }

    /**
     * Gets the value of the statusText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusText() {
        return statusText;
    }

    /**
     * Sets the value of the statusText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusText(String value) {
        this.statusText = value;
    }

    /**
     * Gets the value of the transactionHistorySequenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTransactionHistorySequenceNumber() {
        return transactionHistorySequenceNumber;
    }

    /**
     * Sets the value of the transactionHistorySequenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTransactionHistorySequenceNumber(Integer value) {
        this.transactionHistorySequenceNumber = value;
    }

}
