//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-07/05/2013 05:25 AM(foreman)-)
//


package com.delta.soa.updated.PCiTokenManager;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "PciTokenMgr", targetNamespace = "http://soa.delta.com/pci/soagov/v1", wsdlLocation = "WEB-INF/wsdl/PCiTokenManagerUpdated.wsdl")
public class PciTokenMgr_Service
    extends Service
{

    private final static URL PCITOKENMGR_WSDL_LOCATION;
    private final static WebServiceException PCITOKENMGR_EXCEPTION;
    private final static QName PCITOKENMGR_QNAME = new QName("http://soa.delta.com/pci/soagov/v1", "PciTokenMgr");

    static {
            PCITOKENMGR_WSDL_LOCATION = com.delta.soa.updated.PCiTokenManager.PciTokenMgr_Service.class.getResource("/WEB-INF/wsdl/PCiTokenManagerUpdated.wsdl");
        WebServiceException e = null;
        if (PCITOKENMGR_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'WEB-INF/wsdl/PCiTokenManagerUpdated.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        PCITOKENMGR_EXCEPTION = e;
    }

    public PciTokenMgr_Service() {
        super(__getWsdlLocation(), PCITOKENMGR_QNAME);
    }

    public PciTokenMgr_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PCITOKENMGR_QNAME, features);
    }

    public PciTokenMgr_Service(URL wsdlLocation) {
        super(wsdlLocation, PCITOKENMGR_QNAME);
    }

    public PciTokenMgr_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PCITOKENMGR_QNAME, features);
    }

    public PciTokenMgr_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PciTokenMgr_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PciTokenMgr
     */
    @WebEndpoint(name = "PciTokenMgr_EP")
    public PciTokenMgr getPciTokenMgrEP() {
        return super.getPort(new QName("http://soa.delta.com/pci/soagov/v1", "PciTokenMgr_EP"), PciTokenMgr.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PciTokenMgr
     */
    @WebEndpoint(name = "PciTokenMgr_EP")
    public PciTokenMgr getPciTokenMgrEP(WebServiceFeature... features) {
        return super.getPort(new QName("http://soa.delta.com/pci/soagov/v1", "PciTokenMgr_EP"), PciTokenMgr.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PCITOKENMGR_EXCEPTION!= null) {
            throw PCITOKENMGR_EXCEPTION;
        }
        return PCITOKENMGR_WSDL_LOCATION;
    }

}
