//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-07/05/2013 05:25 AM(foreman)-)
//


package com.delta.soa.updated.PCiTokenManager;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

@WebService(name = "PciTokenMgr", targetNamespace = "http://soa.delta.com/pci/soagov/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PciTokenMgr {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.delta.soa.updated.PCiTokenManager.LookupArrayOfTokensResponse
     */
    @WebMethod(operationName = "LookupArrayOfTokens", action = "LookupArrayOfTokens")
    @WebResult(name = "LookupArrayOfTokensResponse", targetNamespace = "http://soa.delta.com/pci/soagov/v1", partName = "parameters")
    public LookupArrayOfTokensResponse lookupArrayOfTokens(
        @WebParam(name = "LookupArrayOfTokensRequest", targetNamespace = "http://soa.delta.com/pci/soagov/v1", partName = "parameters")
        LookupArrayOfTokensRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.delta.soa.updated.PCiTokenManager.DecodeArrayOfTokensResponse
     */
    @WebMethod(operationName = "DecodeArrayOfTokens", action = "DecodeArrayOfTokens")
    @WebResult(name = "DecodeArrayOfTokensResponse", targetNamespace = "http://soa.delta.com/pci/soagov/v1", partName = "parameters")
    public DecodeArrayOfTokensResponse decodeArrayOfTokens(
        @WebParam(name = "DecodeArrayOfTokensRequest", targetNamespace = "http://soa.delta.com/pci/soagov/v1", partName = "parameters")
        DecodeArrayOfTokensRequest parameters);

}
