//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package com.delta.soa.pci.soagov.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.delta.schemas.pci.v1.requestinfo.PciRequestInfo;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="requestInfo" type="{http://schemas.delta.com/pci/v1/requestinfo}PciRequestInfo"/>
 *         &lt;element name="tokenList" type="{http://soa.delta.com/pci/soagov/v1}ArrayOfString"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "requestInfo",
    "tokenList"
})
@XmlRootElement(name = "DecodeArrayOfTokensRequest")
public class DecodeArrayOfTokensRequest {

    @XmlElement(required = true)
    protected PciRequestInfo requestInfo;
    @XmlElement(required = true)
    protected ArrayOfString tokenList;

    /**
     * Gets the value of the requestInfo property.
     * 
     * @return
     *     possible object is
     *     {@link PciRequestInfo }
     *     
     */
    public PciRequestInfo getRequestInfo() {
        return requestInfo;
    }

    /**
     * Sets the value of the requestInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PciRequestInfo }
     *     
     */
    public void setRequestInfo(PciRequestInfo value) {
        this.requestInfo = value;
    }

    /**
     * Gets the value of the tokenList property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfString }
     *     
     */
    public ArrayOfString getTokenList() {
        return tokenList;
    }

    /**
     * Sets the value of the tokenList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfString }
     *     
     */
    public void setTokenList(ArrayOfString value) {
        this.tokenList = value;
    }

}
