//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package com.delta.soa.pci.soagov.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

@WebService(name = "PciTokenMgr", targetNamespace = "http://soa.delta.com/pci/soagov/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.delta.schemas.pci.v1.requestinfo.ObjectFactory.class,
    com.delta.schemas.pci.v1.pcipan.ObjectFactory.class,
    com.delta.soa.pci.soagov.v1.ObjectFactory.class,
    com.delta.schemas.pci.v1.pcitokenmgrresp.ObjectFactory.class,
    com.delta.schemas.pci.v1.pcitoken.ObjectFactory.class,
    com.delta.schemas.pci.v1.pciitemstat.ObjectFactory.class,
    com.delta.schemas.pci.v1.countryinfo.ObjectFactory.class,
    com.delta.schemas.pci.v1.dictionary.ObjectFactory.class
})
public interface PciTokenMgr {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.delta.soa.pci.soagov.v1.DecodeArrayOfTokensResponse
     */
    @WebMethod(operationName = "DecodeArrayOfTokens", action = "DecodeArrayOfTokens")
    @WebResult(name = "DecodeArrayOfTokensResponse", targetNamespace = "http://soa.delta.com/pci/soagov/v1", partName = "parameters")
    public DecodeArrayOfTokensResponse decodeArrayOfTokens(
        @WebParam(name = "DecodeArrayOfTokensRequest", targetNamespace = "http://soa.delta.com/pci/soagov/v1", partName = "parameters")
        DecodeArrayOfTokensRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.delta.soa.pci.soagov.v1.LookupArrayOfTokensResponse
     */
    @WebMethod(operationName = "LookupArrayOfTokens", action = "LookupArrayOfTokens")
    @WebResult(name = "LookupArrayOfTokensResponse", targetNamespace = "http://soa.delta.com/pci/soagov/v1", partName = "parameters")
    public LookupArrayOfTokensResponse lookupArrayOfTokens(
        @WebParam(name = "LookupArrayOfTokensRequest", targetNamespace = "http://soa.delta.com/pci/soagov/v1", partName = "parameters")
        LookupArrayOfTokensRequest parameters);

}
