//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-07/05/2013 05:25 AM(foreman)-)
//


package com.delta.schemas.SpecialPassengerInfoList;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OnDemandRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OnDemandRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://schemas.delta.com/common/requestinfo/v4}RequestInfo"/>
 *         &lt;element ref="{http://schemas.delta.com/specialpassengerinfolisttypes/v1}OnDemandRequestInfo"/>
 *         &lt;element ref="{http://schemas.delta.com/common/stamping/v2}StampingInfo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OnDemandRequestType", propOrder = {
    "requestInfo",
    "onDemandRequestInfo",
    "stampingInfo"
})
public class OnDemandRequestType {

    @XmlElement(name = "RequestInfo", namespace = "http://schemas.delta.com/common/requestinfo/v4", required = true)
    protected RequestInfoType requestInfo;
    @XmlElement(name = "OnDemandRequestInfo", required = true)
    protected OnDemandRequestInfoType onDemandRequestInfo;
    @XmlElement(name = "StampingInfo", namespace = "http://schemas.delta.com/common/stamping/v2")
    protected StampingInfoType stampingInfo;

    /**
     * Gets the value of the requestInfo property.
     * 
     * @return
     *     possible object is
     *     {@link RequestInfoType }
     *     
     */
    public RequestInfoType getRequestInfo() {
        return requestInfo;
    }

    /**
     * Sets the value of the requestInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestInfoType }
     *     
     */
    public void setRequestInfo(RequestInfoType value) {
        this.requestInfo = value;
    }

    /**
     * Gets the value of the onDemandRequestInfo property.
     * 
     * @return
     *     possible object is
     *     {@link OnDemandRequestInfoType }
     *     
     */
    public OnDemandRequestInfoType getOnDemandRequestInfo() {
        return onDemandRequestInfo;
    }

    /**
     * Sets the value of the onDemandRequestInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link OnDemandRequestInfoType }
     *     
     */
    public void setOnDemandRequestInfo(OnDemandRequestInfoType value) {
        this.onDemandRequestInfo = value;
    }

    /**
     * Gets the value of the stampingInfo property.
     * 
     * @return
     *     possible object is
     *     {@link StampingInfoType }
     *     
     */
    public StampingInfoType getStampingInfo() {
        return stampingInfo;
    }

    /**
     * Sets the value of the stampingInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link StampingInfoType }
     *     
     */
    public void setStampingInfo(StampingInfoType value) {
        this.stampingInfo = value;
    }

}
