//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-07/05/2013 05:25 AM(foreman)-)
//


package com.delta.schemas.SpecialPassengerInfoList;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UserAuthorizationDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UserAuthorizationDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="AgentCityCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="RoleIndicator" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SecurityId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserAuthorizationDataType", namespace = "http://schemas.delta.com/common/userauthdata/v2")
public class UserAuthorizationDataType {

    @XmlAttribute(name = "AgentCityCode")
    protected String agentCityCode;
    @XmlAttribute(name = "RoleIndicator")
    protected String roleIndicator;
    @XmlAttribute(name = "SecurityId")
    protected String securityId;

    /**
     * Gets the value of the agentCityCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgentCityCode() {
        return agentCityCode;
    }

    /**
     * Sets the value of the agentCityCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgentCityCode(String value) {
        this.agentCityCode = value;
    }

    /**
     * Gets the value of the roleIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoleIndicator() {
        return roleIndicator;
    }

    /**
     * Sets the value of the roleIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoleIndicator(String value) {
        this.roleIndicator = value;
    }

    /**
     * Gets the value of the securityId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecurityId() {
        return securityId;
    }

    /**
     * Sets the value of the securityId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecurityId(String value) {
        this.securityId = value;
    }

}
