//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.delta.soa.specialpassengerinfolist;

import javax.xml.ws.WebFault;
import com.delta.schemas.common.fault.v4.BusinessFaultType;

@WebFault(name = "BusinessFault", targetNamespace = "http://schemas.delta.com/common/fault/v4")
public class BusinessFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BusinessFaultType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public BusinessFault(String message, BusinessFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public BusinessFault(String message, BusinessFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.delta.schemas.common.fault.v4.BusinessFaultType
     */
    public BusinessFaultType getFaultInfo() {
        return faultInfo;
    }

}
