//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.delta.soa.specialpassengerinfolist;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "SpecialPassengerInfoList", targetNamespace = "http://soa.delta.com/specialpassengerinfolist", wsdlLocation = "http://webservices5-st:32045/specialpassengerinfolist?wsdl")
public class SpecialPassengerInfoList_Service
    extends Service
{

    private final static URL SPECIALPASSENGERINFOLIST_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.delta.soa.specialpassengerinfolist.SpecialPassengerInfoList_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.delta.soa.specialpassengerinfolist.SpecialPassengerInfoList_Service.class.getResource(".");
            url = new URL(baseUrl, "http://webservices5-st:32045/specialpassengerinfolist?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://webservices5-st:32045/specialpassengerinfolist?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SPECIALPASSENGERINFOLIST_WSDL_LOCATION = url;
    }

    public SpecialPassengerInfoList_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SpecialPassengerInfoList_Service() {
        super(SPECIALPASSENGERINFOLIST_WSDL_LOCATION, new QName("http://soa.delta.com/specialpassengerinfolist", "SpecialPassengerInfoList"));
    }

    /**
     * 
     * @return
     *     returns SpecialPassengerInfoList
     */
    @WebEndpoint(name = "SpecialPassengerInfoList_EP")
    public SpecialPassengerInfoList getSpecialPassengerInfoListEP() {
        return super.getPort(new QName("http://soa.delta.com/specialpassengerinfolist", "SpecialPassengerInfoList_EP"), SpecialPassengerInfoList.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SpecialPassengerInfoList
     */
    @WebEndpoint(name = "SpecialPassengerInfoList_EP")
    public SpecialPassengerInfoList getSpecialPassengerInfoListEP(WebServiceFeature... features) {
        return super.getPort(new QName("http://soa.delta.com/specialpassengerinfolist", "SpecialPassengerInfoList_EP"), SpecialPassengerInfoList.class, features);
    }

}
